---
# tasks file for master


- name: "download jdk software to namenode"
  get_url:
        url:  "http://35.244.242.82/yum/java/el7/x86_64/jdk-8u171-linux-x64.rpm"
        dest: /root
        
- name: "download hadoop software to namenode"
  get_url:
        url:  "https://archive.apache.org/dist/hadoop/common/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm"
        dest: /root

- name: "Installing jdk software on namenode"
  yum:
        name: "{{ jdk_location }}"
        state: present
        disable_gpg_check: yes
  become: true  
  register: java

- name: "Installing hadoop software on namenode"
  shell: "rpm -i /root/hadoop-1.2.1-1.x86_64.rpm  --force"


- name: "creating namenode file"
  file: 
        state: directory
        path: "{{ namenode_path }}"

- name: "configuring hdfs-site.xml file in namenode"
  template:
        dest: "/etc/hadoop/hdfs-site.xml"
        src: "hdfs_master.xml"

- name: "configuring core-site.xml file in namenode"
  template:
        dest: "/etc/hadoop/core-site.xml"
        src: "hdfs_master_core.xml"

- name: "Formating the namenode"
  shell: "echo Y | hadoop namenode -format"
  become: true

- name: "stop hadoop namenode service"
  shell: "hadoop-daemon.sh stop namenode"

- name: "start hadoop namenode service"
  shell: "hadoop-daemon.sh start namenode"
